spring:
  rabbitmq:
    addresses: amqps://gvhdbkkf:JUNfSx-9_nlq03-CXTN0Rw2GyIp_trlQ@moose.rmq.cloudamqp.com/gvhdbkkf

  application:
    name: user-service
  datasource:
    url:  jdbc:postgresql://localhost:5432/user-service
    username: postgres
    password: changeme
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: Always


server:
  port: 8081

rabbit:
  broker:
    exchange:
      userEvent: userevent

ead:
  auth:
    jwtSecret: +MbQeThWmZq4t7w!z%C*F-J@NcRfUjXn2r5u8x/A?D(G+KbPdSgVkYp3s6v9y$B&
    jwtExpiration: 14400000


